export const INSIGHTS = [
  {
    slug: 'the-nigerian-wealth-paradox',
    category: 'Wealth Strategy',
    date: 'March 2026',
    title: 'The Nigerian Wealth Paradox',
    subtitle: 'Why High Income Does Not Always Translate to Financial Control',
    snippet: 'There is a quiet reality in Nigeria\'s upper-income class: many people earn well, but very few operate with true financial clarity. Income flows in. Opportunities appear. Capital moves. But rarely is it structured.',
    image: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?q=80&w=1200&auto=format&fit=crop',
    content: [
      'There is a quiet reality in Nigeria\'s upper-income class: many people earn well, but very few operate with true financial clarity.',
      'Income flows in. Opportunities appear. Capital moves. But rarely is it structured.',
      'What exists instead is fragmentation: land acquired without a clear exit strategy, private deals entered without oversight, idle balances waiting for "the right time."',
      'Over time, this creates activity — but not control.',
      'At Invest-Trust, we believe wealth is not defined by how much you earn, but by how well your capital is coordinated. Control comes from visibility, structure, and disciplined allocation. Without this, even significant income becomes inefficient.',
      'Our long-term view is simple: Wealth should behave like a system — not a series of disconnected decisions.',
      'Because in the end, what matters is not movement. It is direction.',
    ],
  },
  {
    slug: 'idle-cash-is-a-silent-risk',
    category: 'Corporate Finance',
    date: 'March 2026',
    title: 'Idle Cash Is a Silent Risk',
    subtitle: 'What Corporate Treasuries in Nigeria Are Getting Wrong',
    snippet: 'Idle cash is not neutral. It is quietly losing value — to inflation, currency shifts, and missed opportunity. Capital should not only be protected — it should be positioned with structure and intent.',
    image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?q=80&w=1200&auto=format&fit=crop',
    content: [
      'In uncertain environments, many companies choose caution. They hold cash. They wait. They avoid risk.',
      'But in Nigeria, idle cash is not neutral. It is quietly losing value — to inflation, currency shifts, and missed opportunity.',
      'We often see treasury decisions driven by short-term thinking, lack of structured alternatives, and over-reliance on traditional placements.',
      'Yet capital should not only be protected — it should be positioned.',
      'At Invest-Trust, we approach treasury capital with discipline: define liquidity tiers, allocate with structure, and optimize without compromising safety.',
      'Because the goal is not to chase returns. It is to ensure that every naira has a purpose, and every allocation has intent.',
      'The long game is not about reacting to the market. It is about designing how capital behaves within it.',
    ],
  },
  {
    slug: 'beyond-returns',
    category: 'Investment Philosophy',
    date: 'February 2026',
    title: 'Beyond Returns',
    subtitle: 'How Serious Investors Think About Control, Liquidity and Risk',
    snippet: 'Experienced investors focus less on "how much will I make?" and more on how it is structured, what happens under stress, and how easily they can exit. Capital must be managed for both performance and protection.',
    image: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?q=80&w=1200&auto=format&fit=crop',
    content: [
      'Returns are visible. But what truly defines a strong investment is often invisible.',
      'Experienced investors focus less on "how much will I make?" and more on: how is this structured? What happens under stress? How easily can I exit?',
      'In Nigeria, many investments promise upside. Few are designed for resilience.',
      'At Invest-Trust, our philosophy is anchored in one principle: capital must be managed for both performance and protection.',
      'This means clarity of structure, defined liquidity, and disciplined risk oversight.',
      'Because the true test of any investment is not when markets are favorable. It is when conditions change.',
      'And in a market like Nigeria, they always do.',
    ],
  },
  {
    slug: 'the-cost-of-being-busy',
    category: 'Wealth Strategy',
    date: 'February 2026',
    title: 'The Cost of Being Busy',
    subtitle: 'Why Successful Professionals Still Struggle to Build Real Wealth',
    snippet: 'Many high-performing professionals earn well and have clear ambition, yet their wealth lacks structure. The issue is not knowledge — it is bandwidth. Wealth requires not just attention, but discipline and system.',
    image: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?q=80&w=1200&auto=format&fit=crop',
    content: [
      'Many high-performing professionals operate at full capacity. Their time is occupied. Their income is strong. Their ambition is clear.',
      'Yet their wealth often lacks structure.',
      'Investments become opportunistic, relationship-driven, and uncoordinated.',
      'The issue is not knowledge. It is bandwidth.',
      'Wealth requires attention, but more importantly, it requires discipline and system.',
      'At Invest-Trust, we see our role not as replacing the investor, but as introducing structure, continuity, and oversight.',
      'Because wealth is not built in moments. It is built through consistent, intentional decisions over time.',
    ],
  },
  {
    slug: 'when-emergencies-meet-illiquid-investments',
    category: 'Risk Management',
    date: 'January 2026',
    title: 'When Emergencies Meet Illiquid Investments',
    subtitle: 'A Hidden Risk in Nigerian Wealth Building',
    snippet: 'Life does not wait for portfolios to mature. Many investors are heavily exposed to assets that cannot respond quickly — land that cannot be sold, projects that are delayed, structures that are unclear.',
    image: 'https://images.unsplash.com/photo-1434626881859-194d67b2b86f?q=80&w=1200&auto=format&fit=crop',
    content: [
      'Life does not wait for portfolios to mature.',
      'Unexpected events — health issues, business disruptions, family responsibilities — require immediate access to capital.',
      'Yet many investors are heavily exposed to assets that cannot respond quickly: land that cannot be sold, projects that are delayed, structures that are unclear.',
      'This creates a gap between wealth on paper and liquidity in reality.',
      'At Invest-Trust, we approach capital with balance: growth, income, and liquidity.',
      'Because wealth must not only grow. It must remain usable when it matters most.',
    ],
  },
  {
    slug: 'family-legacy-and-money',
    category: 'Legacy Planning',
    date: 'January 2026',
    title: 'Family, Legacy and Money',
    subtitle: 'Why Wealth Without Structure Breaks in One Generation',
    snippet: 'Building wealth requires effort. Preserving it requires structure. Across Nigeria, we see assets without documentation, portfolios without coordination, and wealth without continuity — the result is often fragmentation.',
    image: 'https://images.unsplash.com/photo-1591115765373-5207764f72e7?q=80&w=1200&auto=format&fit=crop',
    content: [
      'Building wealth requires effort. Preserving it requires structure.',
      'Across Nigeria, we have seen assets without documentation, portfolios without coordination, and wealth without continuity.',
      'The result is often the same: disputes, fragmentation, erosion.',
      'At Invest-Trust, we believe wealth should outlive its creator.',
      'That requires clarity of ownership, structured allocation, and long-term planning.',
      'Because true wealth is not what you accumulate. It is what you successfully transfer, protect and sustain.',
    ],
  },
  {
    slug: 'political-cycles-and-your-portfolio',
    category: 'Macro & Policy',
    date: 'December 2025',
    title: 'Political Cycles and Your Portfolio',
    subtitle: 'How Nigerian Elections Quietly Shape Wealth Outcomes',
    snippet: 'In Nigeria, markets do not operate in isolation. Policy decisions influence currency stability, sector performance and capital flow. Long-term success requires understanding not just markets, but the environment in which they operate.',
    image: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?q=80&w=1200&auto=format&fit=crop',
    content: [
      'In Nigeria, markets do not operate in isolation.',
      'Policy decisions influence currency stability, sector performance, and capital flow.',
      'Yet many portfolios are built without acknowledging this reality.',
      'At Invest-Trust, we recognize that investing in Nigeria requires both financial insight and contextual awareness.',
      'Our approach is not reactive. It is adaptive and structured.',
      'Because long-term success comes from understanding not just markets — but the environment in which they operate.',
    ],
  },
  {
    slug: 'health-is-a-financial-asset',
    category: 'Wealth & Wellbeing',
    date: 'December 2025',
    title: 'Health Is a Financial Asset',
    subtitle: 'The Overlooked Link Between Wellness and Wealth',
    snippet: 'Wealth planning often focuses on assets, but rarely on the individual. Health events can disrupt income, investment timelines, and capital stability. At Invest-Trust, we view wealth holistically.',
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?q=80&w=1200&auto=format&fit=crop',
    content: [
      'Wealth planning often focuses on assets. But rarely on the individual.',
      'Health events can disrupt income, investment timelines, and capital stability.',
      'In Nigeria, where healthcare costs can be significant, this risk is amplified.',
      'At Invest-Trust, we view wealth holistically. This includes liquidity planning, contingency buffers, and long-term sustainability.',
      'Because wealth is not only about accumulation. It is about continuity under real-life conditions.',
    ],
  },
  {
    slug: 'real-estate-in-nigeria',
    category: 'Real Estate',
    date: 'November 2025',
    title: 'Real Estate in Nigeria',
    subtitle: 'Asset, Illusion or Liquidity Trap?',
    snippet: 'Real estate remains one of the most trusted assets in Nigeria. But many holdings generate limited income, lack clear exit pathways, and are driven by sentiment rather than structure.',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1200&auto=format&fit=crop',
    content: [
      'Real estate remains one of the most trusted assets in Nigeria. But trust alone does not guarantee performance.',
      'Many holdings generate limited income, lack clear exit pathways, and are driven by sentiment.',
      'At Invest-Trust, we approach real estate differently — not as ownership alone, but as structured exposure, income-generating allocation, and part of a broader portfolio strategy.',
      'Because an asset only creates value when it is aligned with purpose, structure, and timing.',
    ],
  },
  {
    slug: 'the-dealmakers-advantage',
    category: 'Capital Access',
    date: 'November 2025',
    title: "The Dealmaker's Advantage",
    subtitle: 'Why Access, Not Capital, Determines Wealth Outcomes',
    snippet: 'In many markets, capital is the constraint. In Nigeria, access is often the differentiator. Opportunities are relationship-driven and selectively shared. Wealth is shaped not just by how much you have, but by how you are positioned.',
    image: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?q=80&w=1200&auto=format&fit=crop',
    content: [
      'In many markets, capital is the constraint. In Nigeria, access is often the differentiator.',
      'Opportunities are not always visible. They are relationship-driven, selectively shared, and unevenly distributed.',
      'At Invest-Trust, we operate at the intersection of capital, structure, and opportunity.',
      'Our role is not simply to invest. It is to position capital intelligently within the right environments.',
      'Because over the long term, wealth is shaped not just by how much you have, but by where and how you are positioned.',
    ],
  },
];

export type Insight = typeof INSIGHTS[0];
